import Head from 'next/head'
import Link from 'next/link'
import MainLayout from '../layout/MainLayout'
import { fetchFeatured } from '../lib/data'

import Box from './../components/Box'

export default function Home({ data }) {
  const alaroCollection = data.filter(
    (item, index) => item.category === 'alaro'
  )

  const rhodesCollection = data.filter(
    (item, index) => item.category === 'rhodes'
  )

  return (
    <div>
      <Head>
        <title>E-commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainLayout>
        <div className='home'>
          <div className='home-intro-section'>
            <h5>Introducing</h5>
            <Link href='/alaro'>
              <h1>Alaro</h1>
            </Link>
            <h5>The 2022 Collection</h5>
          </div>

          <div className='home-box-container'>
            {alaroCollection.map((item) => (
              <Box
                key={item._id}
                link={`${item.category}/${item.href}`}
                price={item.price}
                name={item.name}
                image={item.image}
                id={item._id}
              />
            ))}
          </div>

          <div className='home-intro-section'>
            <h5>Introducing</h5>
            <Link href='/rhodes'>
              <h1>Rhodes</h1>
            </Link>
            <h5>The 2022 Collection</h5>
          </div>

          <div className='home-box-container'>
            {rhodesCollection.map((item) => (
              <Box
                key={item._id}
                link={`${item.category}/${item.href}`}
                price={item.price}
                name={item.name}
                image={item.image}
                id={item._id}
              />
            ))}
          </div>

          <div className='home-intro-section'>
            <h5>Introducing</h5>
            <Link href='/marbella'>
              <h1>Marbella</h1>
            </Link>
            <h5>The 2022 Collection</h5>
          </div>
        </div>
      </MainLayout>
    </div>
  )
}

export const getStaticProps = async () => {
  const response = await fetchFeatured()
  const data = JSON.parse(JSON.stringify(response))
  return {
    props: {
      data,
    },
  }
}
