import Head from 'next/head'
import Link from 'next/link'
import MainLayout from '../layout/MainLayout'

import Box from './../components/Box'

export default function Home({ data }) {
  const alaroCollection = data.filter(
    (item, index) => item.collection === 'alaro'
  )

  return (
    <div>
      <Head>
        <title>E-commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainLayout>
        <div className='home'>
          <div className='home-intro-section'>
            <h5>Introducing</h5>
            <Link href='/alaro'>
              <h1>Alaro</h1>
            </Link>
            <h5>The 2022 Collection</h5>
          </div>

          <div className='home-box-container'>
            {alaroCollection.map((item) => (
              <Box
                key={item._id}
                link={`${item.collection}/${item.href}`}
                price={item.price}
                name={item.name}
                image={item.image}
              />
            ))}
          </div>
        </div>
      </MainLayout>
    </div>
  )
}

export const getStaticProps = async () => {
  const getFeatured = async () => {
    const request = await fetch('http://localhost:3000/api/products/featured')
    const response = await request.json()
    return response
  }

  const data = await getFeatured()

  return {
    props: {
      data: data,
    },
  }
}
